#!/bin/sh
# SPDX-License-Identifier: MIT
# Generate src/opnames.h from the IORING_OP_* enum in bpf/vmlinux.h so the
# userspace name table always matches the header the BPF side compiled
# against. Re-run after refreshing bpf/vmlinux.h (see tools/gen_vmlinux.sh).
set -eu
VMLINUX=${1:-bpf/vmlinux.h}
OUT=${2:-src/opnames.h}

awk '
/^enum io_uring_op \{/ { inop = 1; next }
inop && /^\};/         { exit }
inop {
	gsub(/[,=].*/, ""); gsub(/[ \t]/, "")
	if ($0 ~ /^IORING_OP_/ && $0 != "IORING_OP_LAST") print $0
}' "$VMLINUX" > /tmp/ops.$$

n=$(wc -l < /tmp/ops.$$)
{
	echo "/* SPDX-License-Identifier: MIT */"
	echo "/* Generated by tools/gen_opnames.sh from $VMLINUX -- do not edit. */"
	echo "#ifndef US_OPNAMES_H"
	echo "#define US_OPNAMES_H"
	echo ""
	echo "static const char *op_names[] = {"
	sed 's/^IORING_OP_\(.*\)$/\t"\1",/' /tmp/ops.$$
	echo "};"
	echo ""
	echo "#define NUM_OP_NAMES $n"
	echo ""
	echo "static inline const char *op_name(unsigned op)"
	echo "{"
	echo "	return op < NUM_OP_NAMES ? op_names[op] : \"OP?\";"
	echo "}"
	echo ""
	echo "#endif /* US_OPNAMES_H */"
} > "$OUT"
rm -f /tmp/ops.$$
echo "wrote $OUT ($n opcodes)"
