/* SPDX-License-Identifier: MIT */
/* Generated by tools/gen_opnames.sh from bpf/vmlinux.h -- do not edit. */
#ifndef US_OPNAMES_H
#define US_OPNAMES_H

static const char *op_names[] = {
	"NOP",
	"READV",
	"WRITEV",
	"FSYNC",
	"READ_FIXED",
	"WRITE_FIXED",
	"POLL_ADD",
	"POLL_REMOVE",
	"SYNC_FILE_RANGE",
	"SENDMSG",
	"RECVMSG",
	"TIMEOUT",
	"TIMEOUT_REMOVE",
	"ACCEPT",
	"ASYNC_CANCEL",
	"LINK_TIMEOUT",
	"CONNECT",
	"FALLOCATE",
	"OPENAT",
	"CLOSE",
	"FILES_UPDATE",
	"STATX",
	"READ",
	"WRITE",
	"FADVISE",
	"MADVISE",
	"SEND",
	"RECV",
	"OPENAT2",
	"EPOLL_CTL",
	"SPLICE",
	"PROVIDE_BUFFERS",
	"REMOVE_BUFFERS",
	"TEE",
	"SHUTDOWN",
	"RENAMEAT",
	"UNLINKAT",
	"MKDIRAT",
	"SYMLINKAT",
	"LINKAT",
	"MSG_RING",
	"FSETXATTR",
	"SETXATTR",
	"FGETXATTR",
	"GETXATTR",
	"SOCKET",
	"URING_CMD",
	"SEND_ZC",
	"SENDMSG_ZC",
	"READ_MULTISHOT",
	"WAITID",
	"FUTEX_WAIT",
	"FUTEX_WAKE",
	"FUTEX_WAITV",
	"FIXED_FD_INSTALL",
	"FTRUNCATE",
	"BIND",
	"LISTEN",
	"RECV_ZC",
	"EPOLL_WAIT",
	"READV_FIXED",
	"WRITEV_FIXED",
	"PIPE",
	"NOP128",
	"URING_CMD128",
};

#define NUM_OP_NAMES 65

static inline const char *op_name(unsigned op)
{
	return op < NUM_OP_NAMES ? op_names[op] : "OP?";
}

#endif /* US_OPNAMES_H */
